name: permission_handler_macos

on:
  push:
    branches: [main, blanc-stable]
    paths:
      - "permission_handler/**"
      - "permission_handler_apple/**"
      - ".github/workflows/permission_handler_macos.yaml"
  pull_request:
    branches: [main, blanc-stable]
    paths:
      - "permission_handler/**"
      - "permission_handler_apple/**"
      - ".github/workflows/permission_handler_macos.yaml"

jobs:
  build:
    name: macOS notification permissions
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Check app facing package
        run: |
          printf '%s\n' 'dependency_overrides:' '  permission_handler_apple:' '    path: ../permission_handler_apple' > pubspec_overrides.yaml
          printf '%s\n' 'dependency_overrides:' '  permission_handler_apple:' '    path: ../../permission_handler_apple' > example/pubspec_overrides.yaml
          flutter pub get
          dart format --output=none --set-exit-if-changed .
          flutter analyze
          flutter test
        working-directory: ./permission_handler

      - name: Check Apple platform package
        run: |
          flutter pub get
          dart format --output=none --set-exit-if-changed .
          flutter analyze
        working-directory: ./permission_handler_apple

      - name: Run Swift tests with code coverage
        run: swift test --enable-code-coverage
        working-directory: ./permission_handler_apple/macos

      - name: Create macOS example
        run: flutter create --platforms=macos --no-pub .
        working-directory: ./permission_handler_apple/example

      - name: Download example dependencies
        run: flutter pub get
        working-directory: ./permission_handler_apple/example

      - name: Run macOS debug build
        run: flutter build macos --debug
        working-directory: ./permission_handler_apple/example
